### ISSUE TITLE
No sco data during hfp_soc_relay run

### ISSUE THREAD

**Issue by insop** [hakanjansson/hfp_sco_relay#1]
Hi @hakanjansson 

Thank you for the code, I have been debugging this for some time and don't find a way forward now, so I am posting this to see any suggestion.

I have run `hfp_soc_relay` successfully on Raspberry Pi 3 A+; however, my two other eval boards including the one using Murata 1LV module doesn't work. More specifically what's not working is, even after both AG and HF connections are established, there is no SCO data is coming, hence [`poll`](https://github.com/hakanjansson/hfp_sco_relay/blob/d4041db66f9d1f1f05a72c8327e4ae7ecdce42c4/hfp_sco_relay.c#L889) loop in `sco_thread_func()` timed out.

I used the same phone and earbuds for all 3 cases, please see the table of setup. I tend to think the issue is not due to chip/board, but the combination of the kernel/bluez.

Let me know if you can think of any thing.

Thank you

![Screen Shot 2020-08-25 at 15 48 19](https://user-images.githubusercontent.com/1240382/91235911-730a9d80-e6eb-11ea-8d36-13bebff4f103.png)

**Comment by hakanjansson** [comment]
Hi @insop 

Have you verified that your devices are configured for SCO routing via Transport (see "Read_SCO_PCM_Int_Param" "Write_SCO_PCM_Int_Param" commands)?

That's really the only thing I can think of but it would definitely fit your description.

**Comment by insop** [comment]
Hi @hakanjansson 

Thank you very much, by changing SCO_Routing from PCM to Transport, CYW43212 is working as RPI3.
I could add `hcitool` command to `systemd` config file, but do you know other way to configure this as a default value?


Please see below for the steps and output.

1. When I do `Read_SCO_PCM_Int_Param`, it was like this, which are
- SCO_Routing: 0x0= pcm
- PCM_Interface_Rate: 0x2, 512 KBps
- Frame_Type: 0x0, short frame
- Sync_Mode: 0x1, Master
- Clock_Mode: 0x1, Master

```
~# hcitool cmd 0x3f 0x1d
< HCI Command: ogf 0x3f, ocf 0x001d, plen 0
> HCI Event: 0x0e plen 9
  01 1D FC 00 00 02 00 01 01 
```

2. So I do the `Write_SCO_PCM_Int_Param` to set the `SCO_Routing` to be transport.

```
# hcitool cmd 0x3f 0x1C 01 02 00 01 01 
< HCI Command: ogf 0x3f, ocf 0x001c, plen 5
  01 02 00 01 01 
> HCI Event: 0x0e plen 4
  01 1C FC 00 
```

Then read back and check it is changed

```
# hcitool cmd 0x3f 0x1d
< HCI Command: ogf 0x3f, ocf 0x001d, plen 0
> HCI Event: 0x0e plen 9
  01 1D FC 00 01 02 00 01 01 
```

- Reference
Page 4, Section 5.3 of https://www.cypress.com/file/298741/download

**Comment by insop** [comment]
Closing the issue and RCA was `SCO_Routing` was set to PCM.
A fix is to change this to `Transport`.
